# Generated by Django 5.0.6 on 2024-06-07 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=120, unique=True)),
                (
                    "course_number",
                    models.PositiveIntegerField(db_index=True, default=1),
                ),
                ("department", models.CharField(default="CS", max_length=200)),
                ("course_credits", models.IntegerField()),
                ("num_lectures", models.PositiveIntegerField()),
                ("instructor_name", models.CharField(default="Deven", max_length=120)),
                ("running", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Prerequisites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_course",
                        to="students.course",
                    ),
                ),
                (
                    "prerequisites",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Courses_Required",
                        to="students.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(default="Deven", max_length=120)),
                ("roll_number", models.CharField(max_length=20, unique=True)),
                ("semester", models.CharField(default="I", max_length=10)),
                ("major", models.CharField(default="CS", max_length=20)),
                (
                    "courses_enrolled",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolled_courses",
                        to="students.course",
                    ),
                ),
            ],
            options={
                "ordering": ["roll_number", "semester"],
            },
        ),
    ]
