# Generated by Django 5.0.6 on 2024-06-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='choices',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='Clothing', max_length=120),
        ),
        migrations.AddField(
            model_name='itemtag',
            name='choices',
            field=models.CharField(choices=[('EC', 'Electronics'), ('CG', 'Clothing'), ('AC', 'Accessories')], default='CG', max_length=2),
        ),
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ManyToManyField(to='core.itemtag'),
        ),
    ]
