# Generated by Django 5.0.6 on 2024-06-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_category_choices_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemimage',
            old_name='image',
            new_name='item_image',
        ),
    ]
