# Generated by Django 5.0.6 on 2024-06-15 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_image_itemimage_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtag',
            name='choices',
        ),
    ]
