# Generated by Django 5.0.6 on 2024-06-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_choice"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Choice",
        ),
    ]
