# Generated by Django 5.0.3 on 2024-03-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.TextField(
                choices=[("DF", "Draft"), ("PB", "Published")],
                default="PB",
                max_length=2,
            ),
        ),
    ]
